
variables:
  - name: case
    value: "build"

parameters:
  - name: stage
    type: string
    default: production
    values: 
      - production
      - Sandbox

stages:
  - stage: productionStage
    jobs:
      - job: job1
        displayName: productionJob
        steps:
          - script: |
            echo $(case)
