
pool: Default

variables:
  - name: case
    value: "build"

parameters:
  - name: stage
    type: string
    default: production
    values: 
      - production
      - Sandbox

stages:
  - stage: productionStage
    jobs:
      - job: job1
        steps:
          - script:
             echo $(case)
